// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/realotz/whole/internal/apps/cms"
	"github.com/realotz/whole/internal/apps/cms/biz"
	"github.com/realotz/whole/internal/apps/cms/data"
	"github.com/realotz/whole/internal/apps/cms/service"
	"github.com/realotz/whole/internal/conf"
	"github.com/realotz/whole/internal/server"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, error) {
	httpServer := server.NewHTTPServer(confServer)
	middleware, err := server.NewMiddleware(confData)
	if err != nil {
		return nil, err
	}
	grpcServer := server.NewGRPCServer(confServer, middleware)
	dataData, err := data.NewData(confData, logger)
	if err != nil {
		return nil, err
	}
	categoryRepo := data.NewCategoryRepo(dataData, logger)
	categoryUsecase := biz.NewCategoryUsecase(categoryRepo, logger)
	categoryServiceServer := service.NewCategoryService(categoryUsecase)
	cmsCms := cms.NewCmsApp(httpServer, grpcServer, middleware, categoryServiceServer)
	app := newApp(logger, cmsCms)
	return app, nil
}
