// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/realotz/whole/internal/services/users/data/ent/employee"
)

// Employee is the model entity for the Employee schema.
type Employee struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Sex holds the value of the "sex" field.
	// 性别
	Sex employee.Sex `json:"sex,omitempty"`
	// UUID holds the value of the "uuid" field.
	// uuid
	UUID uuid.UUID `json:"uuid,omitempty"`
	// Account holds the value of the "account" field.
	//  账号
	Account string `json:"account,omitempty"`
	// Avatar holds the value of the "avatar" field.
	//  avatar
	Avatar string `json:"avatar,omitempty"`
	// Name holds the value of the "name" field.
	// 名称
	Name string `json:"name,omitempty"`
	// Role holds the value of the "role" field.
	// 角色
	Role string `json:"role,omitempty"`
	// NickName holds the value of the "nick_name" field.
	// 昵称
	NickName string `json:"nick_name,omitempty"`
	// Email holds the value of the "email" field.
	// 邮箱
	Email string `json:"email,omitempty"`
	// Mobile holds the value of the "mobile" field.
	// 手机号
	Mobile string `json:"mobile,omitempty"`
	// IDCard holds the value of the "id_card" field.
	// 身份证
	IDCard string `json:"id_card,omitempty"`
	// Birthday holds the value of the "birthday" field.
	// 生日
	Birthday time.Time `json:"birthday,omitempty"`
	// Password holds the value of the "password" field.
	// 密码
	Password string `json:"password,omitempty"`
	// Salt holds the value of the "salt" field.
	// 加密盐
	Salt string `json:"salt,omitempty"`
	// LastIP holds the value of the "last_ip" field.
	// 最后登陆ip
	LastIP string `json:"last_ip,omitempty"`
	// LastTime holds the value of the "last_time" field.
	// 最后登陆时间
	LastTime time.Time `json:"last_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EmployeeQuery when eager-loading is set.
	Edges EmployeeEdges `json:"edges"`
}

// EmployeeEdges holds the relations/edges for other nodes in the graph.
type EmployeeEdges struct {
	// Roles holds the value of the roles edge.
	Roles []*Role `json:"roles,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RolesOrErr returns the Roles value or an error if the edge
// was not loaded in eager-loading.
func (e EmployeeEdges) RolesOrErr() ([]*Role, error) {
	if e.loadedTypes[0] {
		return e.Roles, nil
	}
	return nil, &NotLoadedError{edge: "roles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Employee) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case employee.FieldID:
			values[i] = &sql.NullInt64{}
		case employee.FieldSex, employee.FieldAccount, employee.FieldAvatar, employee.FieldName, employee.FieldRole, employee.FieldNickName, employee.FieldEmail, employee.FieldMobile, employee.FieldIDCard, employee.FieldPassword, employee.FieldSalt, employee.FieldLastIP:
			values[i] = &sql.NullString{}
		case employee.FieldCreateTime, employee.FieldUpdateTime, employee.FieldBirthday, employee.FieldLastTime:
			values[i] = &sql.NullTime{}
		case employee.FieldUUID:
			values[i] = &uuid.UUID{}
		default:
			return nil, fmt.Errorf("unexpected column %q for type Employee", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Employee fields.
func (e *Employee) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case employee.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			e.ID = int64(value.Int64)
		case employee.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				e.CreateTime = value.Time
			}
		case employee.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				e.UpdateTime = value.Time
			}
		case employee.FieldSex:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sex", values[i])
			} else if value.Valid {
				e.Sex = employee.Sex(value.String)
			}
		case employee.FieldUUID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field uuid", values[i])
			} else if value != nil {
				e.UUID = *value
			}
		case employee.FieldAccount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account", values[i])
			} else if value.Valid {
				e.Account = value.String
			}
		case employee.FieldAvatar:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar", values[i])
			} else if value.Valid {
				e.Avatar = value.String
			}
		case employee.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				e.Name = value.String
			}
		case employee.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				e.Role = value.String
			}
		case employee.FieldNickName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nick_name", values[i])
			} else if value.Valid {
				e.NickName = value.String
			}
		case employee.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				e.Email = value.String
			}
		case employee.FieldMobile:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mobile", values[i])
			} else if value.Valid {
				e.Mobile = value.String
			}
		case employee.FieldIDCard:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id_card", values[i])
			} else if value.Valid {
				e.IDCard = value.String
			}
		case employee.FieldBirthday:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field birthday", values[i])
			} else if value.Valid {
				e.Birthday = value.Time
			}
		case employee.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				e.Password = value.String
			}
		case employee.FieldSalt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field salt", values[i])
			} else if value.Valid {
				e.Salt = value.String
			}
		case employee.FieldLastIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_ip", values[i])
			} else if value.Valid {
				e.LastIP = value.String
			}
		case employee.FieldLastTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_time", values[i])
			} else if value.Valid {
				e.LastTime = value.Time
			}
		}
	}
	return nil
}

// QueryRoles queries the "roles" edge of the Employee entity.
func (e *Employee) QueryRoles() *RoleQuery {
	return (&EmployeeClient{config: e.config}).QueryRoles(e)
}

// Update returns a builder for updating this Employee.
// Note that you need to call Employee.Unwrap() before calling this method if this Employee
// was returned from a transaction, and the transaction was committed or rolled back.
func (e *Employee) Update() *EmployeeUpdateOne {
	return (&EmployeeClient{config: e.config}).UpdateOne(e)
}

// Unwrap unwraps the Employee entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (e *Employee) Unwrap() *Employee {
	tx, ok := e.config.driver.(*txDriver)
	if !ok {
		panic("ent: Employee is not a transactional entity")
	}
	e.config.driver = tx.drv
	return e
}

// String implements the fmt.Stringer.
func (e *Employee) String() string {
	var builder strings.Builder
	builder.WriteString("Employee(")
	builder.WriteString(fmt.Sprintf("id=%v", e.ID))
	builder.WriteString(", create_time=")
	builder.WriteString(e.CreateTime.Format(time.ANSIC))
	builder.WriteString(", update_time=")
	builder.WriteString(e.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", sex=")
	builder.WriteString(fmt.Sprintf("%v", e.Sex))
	builder.WriteString(", uuid=")
	builder.WriteString(fmt.Sprintf("%v", e.UUID))
	builder.WriteString(", account=")
	builder.WriteString(e.Account)
	builder.WriteString(", avatar=")
	builder.WriteString(e.Avatar)
	builder.WriteString(", name=")
	builder.WriteString(e.Name)
	builder.WriteString(", role=")
	builder.WriteString(e.Role)
	builder.WriteString(", nick_name=")
	builder.WriteString(e.NickName)
	builder.WriteString(", email=")
	builder.WriteString(e.Email)
	builder.WriteString(", mobile=")
	builder.WriteString(e.Mobile)
	builder.WriteString(", id_card=")
	builder.WriteString(e.IDCard)
	builder.WriteString(", birthday=")
	builder.WriteString(e.Birthday.Format(time.ANSIC))
	builder.WriteString(", password=")
	builder.WriteString(e.Password)
	builder.WriteString(", salt=")
	builder.WriteString(e.Salt)
	builder.WriteString(", last_ip=")
	builder.WriteString(e.LastIP)
	builder.WriteString(", last_time=")
	builder.WriteString(e.LastTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Employees is a parsable slice of Employee.
type Employees []*Employee

func (e Employees) config(cfg config) {
	for _i := range e {
		e[_i].config = cfg
	}
}
