// @ts-ignore
/* eslint-disable */
// Code generated by protoc-gen-ts-umi. DO NOT EDIT.

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.

declare namespace CmsV1 {
	/** CategoryList */
	type CategoryList = {
		message?:string
	}
	/** Category */
	type Category = {
	}
	/** CategoryListOption */
	type CategoryListOption = {
		name?:string
	}
	/** CategoryGetOption */
	type CategoryGetOption = {
		id?:string
	}
	/** CategoryUpdateOption */
	type CategoryUpdateOption = {
		name?:string
	}
	/** CategoryCreateOption */
	type CategoryCreateOption = {
		name?:string
	}
	/** CategoryDeleteOption */
	type CategoryDeleteOption = {
		id?:string
	}
}

