// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/realotz/whole/internal/apps/users/data/ent/member"
	"github.com/realotz/whole/internal/apps/users/data/ent/wechat"
)

// MemberCreate is the builder for creating a Member entity.
type MemberCreate struct {
	config
	mutation *MemberMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (mc *MemberCreate) SetCreateTime(t time.Time) *MemberCreate {
	mc.mutation.SetCreateTime(t)
	return mc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (mc *MemberCreate) SetNillableCreateTime(t *time.Time) *MemberCreate {
	if t != nil {
		mc.SetCreateTime(*t)
	}
	return mc
}

// SetUpdateTime sets the "update_time" field.
func (mc *MemberCreate) SetUpdateTime(t time.Time) *MemberCreate {
	mc.mutation.SetUpdateTime(t)
	return mc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (mc *MemberCreate) SetNillableUpdateTime(t *time.Time) *MemberCreate {
	if t != nil {
		mc.SetUpdateTime(*t)
	}
	return mc
}

// SetSex sets the "sex" field.
func (mc *MemberCreate) SetSex(m member.Sex) *MemberCreate {
	mc.mutation.SetSex(m)
	return mc
}

// SetNillableSex sets the "sex" field if the given value is not nil.
func (mc *MemberCreate) SetNillableSex(m *member.Sex) *MemberCreate {
	if m != nil {
		mc.SetSex(*m)
	}
	return mc
}

// SetUUID sets the "uuid" field.
func (mc *MemberCreate) SetUUID(u uuid.UUID) *MemberCreate {
	mc.mutation.SetUUID(u)
	return mc
}

// SetAccount sets the "account" field.
func (mc *MemberCreate) SetAccount(s string) *MemberCreate {
	mc.mutation.SetAccount(s)
	return mc
}

// SetName sets the "name" field.
func (mc *MemberCreate) SetName(s string) *MemberCreate {
	mc.mutation.SetName(s)
	return mc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (mc *MemberCreate) SetNillableName(s *string) *MemberCreate {
	if s != nil {
		mc.SetName(*s)
	}
	return mc
}

// SetRole sets the "role" field.
func (mc *MemberCreate) SetRole(s string) *MemberCreate {
	mc.mutation.SetRole(s)
	return mc
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (mc *MemberCreate) SetNillableRole(s *string) *MemberCreate {
	if s != nil {
		mc.SetRole(*s)
	}
	return mc
}

// SetNickName sets the "nick_name" field.
func (mc *MemberCreate) SetNickName(s string) *MemberCreate {
	mc.mutation.SetNickName(s)
	return mc
}

// SetNillableNickName sets the "nick_name" field if the given value is not nil.
func (mc *MemberCreate) SetNillableNickName(s *string) *MemberCreate {
	if s != nil {
		mc.SetNickName(*s)
	}
	return mc
}

// SetEmail sets the "email" field.
func (mc *MemberCreate) SetEmail(s string) *MemberCreate {
	mc.mutation.SetEmail(s)
	return mc
}

// SetMobile sets the "mobile" field.
func (mc *MemberCreate) SetMobile(s string) *MemberCreate {
	mc.mutation.SetMobile(s)
	return mc
}

// SetNillableMobile sets the "mobile" field if the given value is not nil.
func (mc *MemberCreate) SetNillableMobile(s *string) *MemberCreate {
	if s != nil {
		mc.SetMobile(*s)
	}
	return mc
}

// SetIDCard sets the "id_card" field.
func (mc *MemberCreate) SetIDCard(s string) *MemberCreate {
	mc.mutation.SetIDCard(s)
	return mc
}

// SetNillableIDCard sets the "id_card" field if the given value is not nil.
func (mc *MemberCreate) SetNillableIDCard(s *string) *MemberCreate {
	if s != nil {
		mc.SetIDCard(*s)
	}
	return mc
}

// SetBirthday sets the "birthday" field.
func (mc *MemberCreate) SetBirthday(t time.Time) *MemberCreate {
	mc.mutation.SetBirthday(t)
	return mc
}

// SetNillableBirthday sets the "birthday" field if the given value is not nil.
func (mc *MemberCreate) SetNillableBirthday(t *time.Time) *MemberCreate {
	if t != nil {
		mc.SetBirthday(*t)
	}
	return mc
}

// SetPassword sets the "password" field.
func (mc *MemberCreate) SetPassword(s string) *MemberCreate {
	mc.mutation.SetPassword(s)
	return mc
}

// SetSalt sets the "salt" field.
func (mc *MemberCreate) SetSalt(s string) *MemberCreate {
	mc.mutation.SetSalt(s)
	return mc
}

// SetLastIP sets the "last_ip" field.
func (mc *MemberCreate) SetLastIP(s string) *MemberCreate {
	mc.mutation.SetLastIP(s)
	return mc
}

// SetNillableLastIP sets the "last_ip" field if the given value is not nil.
func (mc *MemberCreate) SetNillableLastIP(s *string) *MemberCreate {
	if s != nil {
		mc.SetLastIP(*s)
	}
	return mc
}

// SetLastTime sets the "last_time" field.
func (mc *MemberCreate) SetLastTime(t time.Time) *MemberCreate {
	mc.mutation.SetLastTime(t)
	return mc
}

// SetNillableLastTime sets the "last_time" field if the given value is not nil.
func (mc *MemberCreate) SetNillableLastTime(t *time.Time) *MemberCreate {
	if t != nil {
		mc.SetLastTime(*t)
	}
	return mc
}

// SetID sets the "id" field.
func (mc *MemberCreate) SetID(i int64) *MemberCreate {
	mc.mutation.SetID(i)
	return mc
}

// AddWechatIDs adds the "wechats" edge to the Wechat entity by IDs.
func (mc *MemberCreate) AddWechatIDs(ids ...int) *MemberCreate {
	mc.mutation.AddWechatIDs(ids...)
	return mc
}

// AddWechats adds the "wechats" edges to the Wechat entity.
func (mc *MemberCreate) AddWechats(w ...*Wechat) *MemberCreate {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return mc.AddWechatIDs(ids...)
}

// Mutation returns the MemberMutation object of the builder.
func (mc *MemberCreate) Mutation() *MemberMutation {
	return mc.mutation
}

// Save creates the Member in the database.
func (mc *MemberCreate) Save(ctx context.Context) (*Member, error) {
	var (
		err  error
		node *Member
	)
	mc.defaults()
	if len(mc.hooks) == 0 {
		if err = mc.check(); err != nil {
			return nil, err
		}
		node, err = mc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MemberMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mc.check(); err != nil {
				return nil, err
			}
			mc.mutation = mutation
			node, err = mc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(mc.hooks) - 1; i >= 0; i-- {
			mut = mc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MemberCreate) SaveX(ctx context.Context) *Member {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (mc *MemberCreate) defaults() {
	if _, ok := mc.mutation.CreateTime(); !ok {
		v := member.DefaultCreateTime()
		mc.mutation.SetCreateTime(v)
	}
	if _, ok := mc.mutation.UpdateTime(); !ok {
		v := member.DefaultUpdateTime()
		mc.mutation.SetUpdateTime(v)
	}
	if _, ok := mc.mutation.Sex(); !ok {
		v := member.DefaultSex
		mc.mutation.SetSex(v)
	}
	if _, ok := mc.mutation.UUID(); !ok {
		v := member.DefaultUUID()
		mc.mutation.SetUUID(v)
	}
	if _, ok := mc.mutation.Name(); !ok {
		v := member.DefaultName
		mc.mutation.SetName(v)
	}
	if _, ok := mc.mutation.Role(); !ok {
		v := member.DefaultRole
		mc.mutation.SetRole(v)
	}
	if _, ok := mc.mutation.NickName(); !ok {
		v := member.DefaultNickName
		mc.mutation.SetNickName(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MemberCreate) check() error {
	if _, ok := mc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New("ent: missing required field \"create_time\"")}
	}
	if _, ok := mc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New("ent: missing required field \"update_time\"")}
	}
	if _, ok := mc.mutation.Sex(); !ok {
		return &ValidationError{Name: "sex", err: errors.New("ent: missing required field \"sex\"")}
	}
	if v, ok := mc.mutation.Sex(); ok {
		if err := member.SexValidator(v); err != nil {
			return &ValidationError{Name: "sex", err: fmt.Errorf("ent: validator failed for field \"sex\": %w", err)}
		}
	}
	if _, ok := mc.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New("ent: missing required field \"uuid\"")}
	}
	if _, ok := mc.mutation.Account(); !ok {
		return &ValidationError{Name: "account", err: errors.New("ent: missing required field \"account\"")}
	}
	if v, ok := mc.mutation.Account(); ok {
		if err := member.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf("ent: validator failed for field \"account\": %w", err)}
		}
	}
	if _, ok := mc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New("ent: missing required field \"email\"")}
	}
	if _, ok := mc.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New("ent: missing required field \"password\"")}
	}
	if v, ok := mc.mutation.Password(); ok {
		if err := member.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf("ent: validator failed for field \"password\": %w", err)}
		}
	}
	if _, ok := mc.mutation.Salt(); !ok {
		return &ValidationError{Name: "salt", err: errors.New("ent: missing required field \"salt\"")}
	}
	if v, ok := mc.mutation.Salt(); ok {
		if err := member.SaltValidator(v); err != nil {
			return &ValidationError{Name: "salt", err: fmt.Errorf("ent: validator failed for field \"salt\": %w", err)}
		}
	}
	return nil
}

func (mc *MemberCreate) sqlSave(ctx context.Context) (*Member, error) {
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	if _node.ID == 0 {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	return _node, nil
}

func (mc *MemberCreate) createSpec() (*Member, *sqlgraph.CreateSpec) {
	var (
		_node = &Member{config: mc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: member.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: member.FieldID,
			},
		}
	)
	if id, ok := mc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := mc.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: member.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := mc.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: member.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := mc.mutation.Sex(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: member.FieldSex,
		})
		_node.Sex = value
	}
	if value, ok := mc.mutation.UUID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: member.FieldUUID,
		})
		_node.UUID = value
	}
	if value, ok := mc.mutation.Account(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: member.FieldAccount,
		})
		_node.Account = value
	}
	if value, ok := mc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: member.FieldName,
		})
		_node.Name = value
	}
	if value, ok := mc.mutation.Role(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: member.FieldRole,
		})
		_node.Role = value
	}
	if value, ok := mc.mutation.NickName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: member.FieldNickName,
		})
		_node.NickName = value
	}
	if value, ok := mc.mutation.Email(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: member.FieldEmail,
		})
		_node.Email = value
	}
	if value, ok := mc.mutation.Mobile(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: member.FieldMobile,
		})
		_node.Mobile = value
	}
	if value, ok := mc.mutation.IDCard(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: member.FieldIDCard,
		})
		_node.IDCard = value
	}
	if value, ok := mc.mutation.Birthday(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: member.FieldBirthday,
		})
		_node.Birthday = value
	}
	if value, ok := mc.mutation.Password(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: member.FieldPassword,
		})
		_node.Password = value
	}
	if value, ok := mc.mutation.Salt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: member.FieldSalt,
		})
		_node.Salt = value
	}
	if value, ok := mc.mutation.LastIP(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: member.FieldLastIP,
		})
		_node.LastIP = value
	}
	if value, ok := mc.mutation.LastTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: member.FieldLastTime,
		})
		_node.LastTime = value
	}
	if nodes := mc.mutation.WechatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.WechatsTable,
			Columns: []string{member.WechatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: wechat.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MemberCreateBulk is the builder for creating many Member entities in bulk.
type MemberCreateBulk struct {
	config
	builders []*MemberCreate
}

// Save creates the Member entities in the database.
func (mcb *MemberCreateBulk) Save(ctx context.Context) ([]*Member, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Member, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				if nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MemberCreateBulk) SaveX(ctx context.Context) []*Member {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
